import Header from "@/components/Header";
import MainProvider from "@/providers/MainProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Complete IELTS Course",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <MainProvider>
        <body>
          <Header />
          {children}
        </body>
      </MainProvider>
    </html>
  );
}
